# action.yml
name: 'Build Installer'
description: 'Build an installer'
inputs:
  name:
    description: 'Name of the image'
    required: true
    default: 'name'
  version:
    description: 'version for the Chart/App'
    required: true
    default: '0.0.0'
  path:
    description: 'path for helmchart folder'
    required: true
outputs:
  filename:
    description: 'The name of the docker file'
    value: ${{ steps.buildhelmpackage.outputs.filename }}
runs:
  using: 'composite'
  steps:
    - name: Build Helm Package
      id: buildhelmpackage
      shell: bash
      run: |
        helm version
        sed -i -e 's/1.0.0/${{ inputs.version }}/g' "${{ inputs.path }}/Chart.yaml"
        echo "---------"
        cat "${{ inputs.path }}/Chart.yaml"
        echo "---------"
        helm lint "${{ inputs.path }}"
        helm package "${{ inputs.path }}"
        ls -las
        echo "filename=${{ inputs.name }}-${{ inputs.version }}.tgz" >> $GITHUB_OUTPUT
