# action.yml
name: 'Build Installer'
description: 'Build an installer'
inputs:
  name:
    description: 'Name of the image'
    required: true
    default: 'name'
  tag:
    description: 'tag for the image'
    required: true
    default: 'latest'
  path:
    description: 'path for dockerfile folder'
    required: true
outputs:
  filename:
    description: 'The name of the docker file'
    value: ${{ steps.builddockerimage.outputs.filename }}
runs:
  using: 'composite'
  steps:
    - name: Build Docker image
      id: builddockerimage
      shell: bash
      run: |
        # Install Helm
        #wget https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
        #tar xvf helm-v3.9.3-linux-amd64.tar.gz
        #sudo mv linux-amd64/helm /usr/local/bin
        #ls -las
        #rm helm-v3.4.1-linux-amd64.tar.gz
        #rm -rf linux-amd64
        helm version
